### ISSUE TITLE
サイト読込中に使用できない

### ISSUE THREAD

**Issue by kanap0nta** [kanap0nta/QuickDrag-WE#17]
サイト読込中でも使用できるようにする
方法不明。どなたか方法教えてください。

**Comment by c0urageF** [comment]
onloadイベントは試しましたか？
https://www.tam-tam.co.jp/tipsnote/javascript/post601.html

**Comment by c0urageF** [comment]
ページ読み込み時に quickdrag.jsのaddEventListenerを発火させていってことですよね？

**Comment by kanap0nta** [comment]
manifest.jsonのcontent_scriptsに下記を追記
"run_at" : "document_start",
