### ISSUE TITLE
Problem with this website

### ISSUE THREAD

**Issue by xenio** [kanap0nta/QuickDrag-WE#52]
There is the same problem with this website (image post are not loading) :
https://thehackernews.com
The extension is causing this error:
Error: Permission denied to access property "__rocketLoaderInlineHandlerProxy"[Learn More] rocket-loader.min.js:1:8863 

Cloudflare rocket-loader is not loading.

If I disable the Extension the website is ok.

**Comment by kanap0nta** [comment]
Thank you for reporting the problem.
I fixed this problem.

**Comment by kolte** [comment]
what was the fix?

**Comment by kanap0nta** [comment]
> 
> 
> what was the fix?
I stopped using overload function when window was loaded.

window.onload = function() { // omitted 
}
→
window.addEventListener("load", function() {  // omitted 
}, false);
