### ISSUE TITLE
Use 'openerTabId' parameter on calling tabs.create()

### ISSUE THREAD

**Issue by garywill** [kanap0nta/QuickDrag-WE#68]
According to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create):

> openerTabId Optional
>     integer. The ID of the tab that opened this tab. If specified, the opener tab must be in the same window as the newly created tab.

If you install [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/), you can see that generally new tabs opened by a web are in sub-tree of the parent tab.

**Currently** QuickDrag-WE's opening behavior (tested on Firefox 78):
- **drag a link before** doing anything, new tab **will not be** in the corresponding sub-tree
- click a link with `target="_blank"` attribute, **then drag a link**, new tab **will be** in the corresponding sub-tree

QuickDrag-WE **should always** (or have an option to) make drag-opened new tabs in the corresponding sub-tree. So `openerTabId` should be used.

**Comment by kanap0nta** [comment]
Thanks for the bug report.
I fixed the issues you mentioned.
If you set it to "New tab position Left", the problem occurs because there is a problem with Tree Style Tab.
