### ISSUE TITLE
ダークモードへの対応とポップアップが少し崩れる問題

### ISSUE THREAD

**Issue by surapunoyousei** [kanap0nta/QuickDrag-WE#81]
Ubuntu を使用しており、スクリーンショットを撮影しようとするとポップアップがとじてしまうので、写真で失礼します。
以下の通り、ダークテーマにしてみました。このようなダークテーマに対応する予定はありますか？
また現行のquick Dragでは検索エンジンのURLの欄が大きすぎかもしれません。

<img src="https://user-images.githubusercontent.com/73892113/136876868-97ede88d-6081-4a0b-93bc-ca586d948d1f.png" width="50%">

**Comment by kanap0nta** [comment]
#83
